### ISSUE TITLE
ngxfoundation.com Website SSL Certificate expired

### ISSUE THREAD

**Issue by audiofreak1** [nthompson777/ngx-foundation#10]
Hi, sorry, maybe this is not the right place, but your SSL certificate on your demo site https://ngxfoundation.com/ is expired.

Thanks for your efforts!

**Comment by audiofreak1** [comment]
Now also the complete website https://www.ngxfoundation.com/ is gone.

**Comment by nthompson777** [comment]
Thanks @audiofreak1 This was fixed yesterday.
